### ISSUE TITLE
Tabletalk topic 2023

### ISSUE THREAD

**Issue by shahidatulnabila** [ohbm/osr2023#2]
![TableTalk_template](https://github.com/ohbm/osr2023/assets/134462791/a48b1ba9-ab68-443a-80e1-e1286e3cc237)
![TableTalk_template (1)](https://github.com/ohbm/osr2023/assets/134462791/f71ec8d2-85f6-4064-abcb-7769010b9e29)
![TableTalk_template (2)](https://github.com/ohbm/osr2023/assets/134462791/10f40bbc-d3ce-4e04-975e-f0c7de419bc6)
![TableTalk_template (3)](https://github.com/ohbm/osr2023/assets/134462791/48bb2466-9b59-4488-baa7-c17600513a72)
![TableTalk_template (4)](https://github.com/ohbm/osr2023/assets/134462791/0da410b8-4b11-475a-9bd1-bbcdd8fbf872)

**Comment by AdaGondova** [comment]
Thanks!
